mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    path('index2/', views.index2, name='index2'),
    path('booked/', views.booked, name='booked'),

    path('review/<int:shop_area>/', views.review, name='review'),
    path('shop_detail/', views.shop_detail, name='shop_detail'),

    path('booking/<int:shop_area>/', views.booking, name='booking'),

    path('register/', views.register, name='register'),
    path('guide/', views.guide, name='guide'),

    path('profile/', views.profile, name='profile'),


    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),


    path('edit_shop/<int:shop_id>/', views.edit_shop, name='edit_shop'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('edit_pic/', views.edit_pic, name='edit_pic'),

    path('delete/<int:shop_area>/', views.delete_shop, name='delete_shop'),
    path('delete/', views.delete, name='delete'),

    path('adminx/', views.adminx, name='adminx')

]

mysite/polls/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User

# users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


# project
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='img/user', blank=True)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)


class Zone(models.Model):
    zone_type = models.CharField(max_length=50)

class ShopArea(models.Model):
    area_code = models.CharField(max_length=10)
    del_shop = models.BooleanField(default=False)
    isBooking = models.BooleanField(default=False)
    shop_owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    WAIT = 'รอการอนุมัติ'
    APPROVE = 'อนุมัติ'
    NAPPROVE = 'ไม่อนุมัติ'
    TYPES2 = (
        (WAIT, 'รอการอนุมัติ'),
        (APPROVE, 'อนุมัติ'),
        (NAPPROVE, 'ไม่อนุมัติ')
    )
    approve_status = models.CharField(max_length=12, choices=TYPES2, default='ไม่อนุมัติ')

    def __str__(self):
        return self.area_code


class Shop(models.Model):
    shop_name = models.CharField(max_length=100)
    shop_open = models.TimeField(null=True, blank=True)
    shop_close = models.TimeField(null=True, blank=True)
    shop_detail = models.CharField(null = True, blank=True, max_length=500)
    shop_booking = models.DateField(null=True)
    shop_area = models.ForeignKey(ShopArea, on_delete=models.PROTECT, default=1)
    shop_owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    image = models.ImageField(upload_to='img/', blank=True)

    def __str__(self):
        return self.shop_name



class Review(models.Model):
    review_title = models.CharField(max_length=100)
    review_message = models.CharField(max_length=500)
    review_shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    review_user = models.ForeignKey(User, on_delete=models.PROTECT, default=1)
    day = models.CharField(max_length=100, null=True)

    def __str__(self):
        return  self.review_title

class Hotel(models.Model):
    name = models.CharField(max_length=50)
    hotel_Main_Img = models.ImageField(upload_to='images/')


class Payment(models.Model):
    WAIT = 'รอตรวจสอบ'
    APPROVE = 'จ่ายแล้ว'
    NAPPROVE = 'ค้างชำระ'
    TYPES = (
        (WAIT, 'รอตรวจสอบ'),
        (APPROVE, 'จ่ายแล้ว'),
        (NAPPROVE, 'ค้างชำระ')
    )
    payment_status = models.CharField(choices=TYPES, default='รอตรวจสอบ', max_length=100)
    payment_price = models.IntegerField(default=0)
    payment_date = models.DateField(null=True)
    user_payment = models.ForeignKey(User, on_delete=models.PROTECT)
    payment_shop = models.ForeignKey(Shop, on_delete=models.PROTECT)


class Event(models.Model):
    event_date = models.DateField(null=True)
    event_desc = models.CharField(max_length=500)
    event_zone = models.ForeignKey(Zone, on_delete=models.PROTECT)

mysite/polls/views.py
import datetime
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
from django.forms import formset_factory
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
# Create your views here.
from django.views import View

from .models import Review, Shop, ShopArea, UserProfile

from .forms import ReviewForm, EditProfileForm, RegistrationForm, BookingForm, UserProfileForm

@login_required()
@permission_required('polls.change_shop')
def shop_detail(request):
    shoplink = Shop.objects.filter(shop_owner=request.user.id)
    print(shoplink)
    if shoplink:
        context = {
            'shoplink' : shoplink
        }
    else:
        context = {
            'shoplink' : 'Nodata'
        }
    return render(request, 'polls/shop_detail.html', context=context)

@login_required()
def profile(request):
    args = {'user' : request.user}

    return render(request, 'polls/profile.html', args)

@login_required()
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST,request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form' : form}
        return render(request, template_name='polls/edit_profile.html', context=args)


@login_required()
def edit_pic(request):
    a = UserProfile.objects.get(user_id=request.user.id)
    b = UserProfile.objects.filter(user_id=request.user.id)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = UserProfileForm(instance=a)

    context = {
    'form': form,
    'shop': b
     }
    return render(request, template_name='polls/edit_pic.html', context=context)


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            print(request.POST.get('choices'))
            if request.POST.get('choices') == '01':

                group = Group.objects.get(name='User')
                user.groups.add(group)
            else:
                group = Group.objects.get(name='Merchant')
                user.groups.add(group)
            return redirect('login')
    else:
        form = RegistrationForm()

    args = {'form': form}
    return render(request, template_name='polls/register.html', context=args)


def adminx(request):
    return redirect('/admin')



def guide(request):
    context = {}
    return render(request, 'polls/guide.html', context=context)


def my_login(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)

            next_url = request.POST.get('next_url')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('index2')
        else:
            context['username'] = username
            context['password'] = password
            context['error'] = 'Wrong username or password'

    next_url = request.GET.get('next')
    if next_url:
        context['next_url'] = next_url

    return render(request, template_name='polls/login.html', context=context)

def my_logout(request):
    logout(request)
    return redirect('login')

def index2(request):

    # query_set = Group.objects.filter(user=request.user)
    # group_name = ''
    # for g in query_set:
    #     group_name = g.name


    shop_list = ShopArea.objects.all()
    shop_listz = ShopArea.objects.all()[0:1]

    line_1 = ShopArea.objects.all()[0:34:-1]
    line_2 = ShopArea.objects.all()[76:101:-1]
    line_3 = ShopArea.objects.all()[101:126:-1]
    line_4 = ShopArea.objects.all()[127:144:-1]
    line_5 = ShopArea.objects.all()[38:45]
    line_6 = ShopArea.objects.all()[145:160:-1]
    line_7 = ShopArea.objects.all()[45:62]


    line_extra = ShopArea.objects.all()[62:72]
    line_extra2 = ShopArea.objects.all()[72:76]

    shop = Shop.objects.all()


    context = {
        'shop_list' : shop_list,
        'shop_listz' : shop_listz,
        'line_1' : line_1,
        'line_2' : line_2,
        'line_3' : line_3,
        'line_4' : line_4,
        'line_5' : line_5,
        'line_6' : line_6,
        'line_7' : line_7,
        'line_extra' : line_extra,
        'line_extra2' : line_extra2,
        'user' : request.user,
        'shopr': shop,
    }
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)

            return redirect('index')
        else:
            context['username'] = username
            context['password'] = password
            context['error'] = 'Wrong username or password'



    return render(request, template_name='polls/index2.html', context=context)

def review(request, shop_area):
    area = ShopArea.objects.get(pk=shop_area)
    shoplink = Shop.objects.get(shop_area=shop_area)
    now = datetime.date.today()

    print(now)
    # การเอาข้อมูลมาแสดง
    # review_list = Review.objects.all()

    ##ส่วนของฐานข้อมูล

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        user = User.objects.get(id=request.user.id)
        if form.is_valid():
            review = Review.objects.create(
                review_title = form.cleaned_data.get('review_title'),
                review_message = form.cleaned_data.get('review_message'),
                review_shop_id = shoplink.id,
                day = now,
                review_user = user
            )
    else:
        form = ReviewForm()


    context = {
        'page_title' : 'wellcome to my poll page',
        'area' : area,
        'form' : form,
        'user' : request.user
    }

    return render(request, template_name='polls/review.html', context=context)


@login_required()
@permission_required('polls.add_shop')
def booking(request, shop_area):
    area = ShopArea.objects.get(pk=shop_area)
    now = datetime.date.today()
    print(now)
    # การเอาข้อมูลมาแสดง
    # review_list = Review.objects.all()

    ##ส่วนของฐานข้อมูล

    if request.method == 'POST':
        form = BookingForm(request.POST, request.FILES)
        user = User.objects.get(id=request.user.id)
        shopArea = ShopArea.objects.get(id=shop_area)
        shop_list = []

        for i in Shop.objects.filter(shop_owner_id=request.user.id):
            shop_list.append(i.shop_name)

        if len(shop_list) != 0:
            if request.POST.get('shop_name') in shop_list:
                shop_data = Shop.objects.get(shop_name=request.POST.get('shop_name'))
                print('ohm')

                for i in Shop.objects.filter(shop_owner_id=request.user.id):

                    if shop_data.shop_name == i.shop_name and shop_data.shop_owner_id == request.user.id:
                        shop_data.shop_area = area
                        shopArea.isBooking = 1
                        shopArea.shop_owner = user

                        shopArea.save()
                        shop_data.save()
                        print(shopArea.isBooking)
                        return redirect('booked')
                        break

            else:
                print('dorn')
                if form.is_valid() and shopArea.isBooking != 1:
                    print('earth')
                    shop = Shop.objects.create(
                        shop_name=form.cleaned_data.get('shop_name'),
                        shop_open=form.cleaned_data.get('shop_open'),
                        shop_close=form.cleaned_data.get('shop_close'),
                        shop_detail=form.cleaned_data.get('shop_detail'),
                        image=request.FILES.get('image'),
                        shop_area=area,
                        shop_owner=user,
                        shop_booking= now,


                    )
                    shopArea.isBooking = 1
                    shopArea.approve_status = 'รอการอนุมัติ'
                    shopArea.shop_owner = user
                    shopArea.save()
                    print(shopArea.isBooking)
                    return redirect('booked')


        else:
            if form.is_valid() and shopArea.isBooking != 1:
                print('earth')
                shop = Shop.objects.create(
                    shop_name=form.cleaned_data.get('shop_name'),
                    shop_open=form.cleaned_data.get('shop_open'),
                    shop_close=form.cleaned_data.get('shop_close'),
                    shop_detail=form.cleaned_data.get('shop_detail'),
                    image=request.FILES.get('image'),
                    shop_area=area,
                    shop_owner=user,
                    shop_booking=now

                )
                shopArea.isBooking = 1
                shopArea.approve_status = 'รอการอนุมัติ'
                shopArea.shop_owner = user
                shopArea.save()

                print(shopArea.isBooking)
                return redirect('booked')


    else:
        form = BookingForm()

    context = {
        'page_title': 'welcome to my poll page',
        'area': area,
        'form': form,

    }

    return render(request, template_name='polls/booking.html', context=context)



@login_required()
@permission_required('polls.add_shop')
def booked(request):

    # query_set = Group.objects.filter(user=request.user)

mysite/polls/templates/polls/booking.html
<!DOCTYPE html> {% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Booking</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'polls/css/book.css' %}" />

    <link
      href="https://fonts.googleapis.com/css?family=Athiti:500"
      rel="stylesheet"
    />
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index2' %}">
          <img src="../../../media/img/train.png" width="50px" /> KMITL MARKET
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index2' %}"
                >Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% if perms.polls.delete_shop %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'delete' %}"> delete shop</a>
            </li>

            {% endif %} {% if perms.polls.add_shop %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'booked' %}"> Book</a>
            </li>
            {% endif %} {% if not user.is_authenticated %}
            <li class="nav-item">
              <div class="nav-link">|</div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}"> Login</a>
            </li>
            {% else %}
            <li class="nav-item">
              <div class="nav-link">|</div>
            </li>

            <div class="dropdown">
              <button
                class="btn btn-secondary dropdown-toggle"
                type="button"
                id="dropdownMenu2"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                {{ user }}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <a href="{% url 'profile' %}"
                  ><button class="dropdown-item" type="button">
                    Profile
                  </button></a
                >
                {% if perms.polls.add_shop %}
                <a href="{% url 'shop_detail' %}"
                  ><button class="dropdown-item" type="button">
                    Edit Shop
                  </button></a
                >
                {% endif %}
                <a href="{% url 'logout' %}"
                  ><button class="dropdown-item" type="button">
                    Log out
                  </button></a
                >
              </div>
            </div>

            {% endif %} {% if not user.is_authenticated %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}"> Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% if area.isBooking %}

    <br /><br /><br /><br />
    <div
      class="text-center container"
      style="background-color: white; height: 400px;"
    >
      <h1 style="color: red; position: absolute; left: 40%; top: 8em">
        ร้านถูกจองไปแล้วจ้า
      </h1>
    </div>
    {% else%}

    <br />
    <div class="container">
      <form
        enctype="multipart/form-data"
        method="post"
        class="w-50 p-4 m-auto"
        style="background-color: white;"
        id="#frameA"
      >
        {% csrf_token %}

        <h1 class="text-center">ZONE : {{ area.area_code }}</h1>

        {% if form.non_field_errors %}
        <p>
          {{ form.non_field_errors }}
        </p>
        {% endif %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-warning w-100">Submit</button>
      </form>
      <br />
    </div>

    {% endif %}

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

mysite/polls/templates/polls/review.html
<!DOCTYPE html> {% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>review</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Athiti:500" rel="stylesheet">
{#  <link rel="stylesheet" href="{% static 'polls/css/review_style.css' %}">#}

  
</head>


  <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index2' %}">
                <img src="../../../media/img/train.png" width="50px"> KMITL MARKET
        </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index2' %}">Home
                <span class="sr-only">(current)</span>
              </a>
        </li>
       {% if perms.polls.delete_shop %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'delete' %}">  delete shop</a>
              </li>


        {% endif %}
 {% if perms.polls.add_shop %}
              <li class="nav-item">

              <a class="nav-link" href="{% url 'booked' %}">  Book</a>
              </li>
          {% endif %}

          {% if not user.is_authenticated %}
             <li class="nav-item">
                 <div class="nav-link">|</div>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"> Login</a>
            </li>
          {% else %}
               <li class="nav-item">
                 <div class="nav-link">|</div>
            </li>

              <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {{ user }}
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <a href="{% url 'profile' %}"><button class="dropdown-item" type="button">Profile</button></a>
 {% if perms.polls.add_shop %}
    <a href="{% url 'shop_detail' %}"><button class="dropdown-item" type="button">Edit Shop</button></a>
     {% endif %}
      <a href="{% url 'logout' %}"><button class="dropdown-item" type="button">Log out</button></a>

  </div>
</div>

          {% endif %}
                {% if not user.is_authenticated %}

                    <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}"> Sign Up</a>
            </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>




<div>
  
  <div class="container">
    
    <div class="row mt-5 border p-4" id="shopPage">
      <div class="col-5 text-center">

        {% for shopname in area.shop_set.all %}

        {% if shopname.image %}
        <img src="{{ shopname.image.url }}" width="300px" height="300" style="border-radius: 20px">

        {% else %}
        <img src="../../../media/img/no-img.png" width="300px" height="300px">
        {% endif %}
        {% endfor %}
        <br>

        {% if user.id %}
        <button type="button" class="btn btn-warning mt-4 w-100" data-toggle="modal" data-target="#reviewWriteForm">Review</button>

        {% else %}

        <button type="button" class="btn btn-warning mt-4 w-100" data-toggle="modal" data-target="#reviewError">Review</button>
        You have to <a href="{% url 'login' %}">login</a> before 'REVIEW'

        {% endif %}
        <input type="hidden" name="next_url" value="{{ next_url }}">

      </div>
      <div class="col-7">
        {% for shopname in area.shop_set.all %}

        <div class="row mt-4 mb-4">
          <div class="col-2">
            <img src="../../../media/img/store.png" width="50px">
          </div>
          <div class="col-10">
            <h2>ร้าน : {{ shopname.shop_name}}</h2>
          </div>
        </div>
        <hr>

        <div class="row mt-4 mb-4">
          <div class="col-2">
            <img src="../../../media/img/open.png" width="50px">

          </div>
          <div class="col-10">
            <h3>
                {% if shopname.shop_open and shopname.shop_close %}
                Open : {{ shopname.shop_open }} - {{ shopname.shop_close }}
                {% elif shopname.shop_open and not shopname.shop_close %}
                    Open : {{ shopname.shop_open }}
                {% elif not shopname.shop_open and shopname.shop_close %}
                    Close : {{ shopname.shop_close }}
                {% else %}
                    -
                {% endif %}
            </h3>
          </div>
        </div>

        <div class="row mt-4 mb-4">
          <div class="col-2">
            <img src="../../../media/img/event.png" width="50px">

          </div>
          <div class="col-10">
            <h5 class="text-justify">{{ shopname.shop_detail}} </h5>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    
    <div class="modal fade bd-example-modal-lg" id="reviewWriteForm" tabindex="-1" role="dialog" aria-labelledby="reviewWriteForm" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content p-5">
          
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button><br>
            <p class="text-center h3"> กรอกข้อมูลสำหรับรีวิว</p>
            
            <hr>
            
            {% for shopname in area.shop_set.all %}
            
            
            {% endfor %}
            <form method="post" action="{% url 'review' area.id %}">
              {% csrf_token %}
              
              
              
              <div class="form-group">
                
                <label>หัวข้อ : </label>
                {{ form.review_title }}
                
                <label>รายละเอียด : </label>
                {{ form.review_message }}
              </div>
              <div class="row" width="50%">
                <div class="col-6 text-right">  <button type="submit" class="btn btn-warning w-50">Submit</button></div>
                <div class="col-6 text-left"><button type="button" class="btn btn-secondary w-50" data-dismiss="modal">CANCLE</button></div>
              </div>
            </form>
            
          </div>
        </div>
      </div>
    </div>

    {% for market in area.shop_set.all %}
    {% for review in market.review_set.all %}

    <div class="row mt-2 p-4 border" style="background-color: white;">

      <div class="col-4">
        {% if review.review_user.userprofile.image %}
        <img src=" {{review.review_user.userprofile.image.url}}" width="300px" height="300">

        {% else %}
        <img src="../../../media/img/no-img.png" width="300px" height="300px">
        {% endif %}


      </div>
      <div class="col-8">


        <p style="color:gray; display: block; text-align: right; margin-bottom: 10px;"><i><b><button type="button" class="btn btn-warning btn-sm" style="border-radius: 100px" disabled>Comment {{ forloop.counter }} </button>
        </b></i></p>

        <h4>Title :   {{ review.review_title }}</h4>


        <p> {{ review.review_message }}</p>

        <small class="mr-4" style="color:gray;"><i>

          Create by : {{review.review_user.get_full_name}} </i></small>
          <small style="color:gray;"><i>Create Date : {{review.day}}</i></small>
        </div>

      </div>
      {% endfor%}

      {% endfor %}

    </div>
    

</div>
    

  
  
  <style>


body {
    font-family: 'Athiti', sans-serif;
  background: url(../../../media/img/photolog.jpg) no-repeat center center fixed;
  background-blend-mode: darken;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

.jumbotron {
    background-position: center;

    height: 500px;

}
.jumbotron h1 {
    margin: auto;
    text-align: center;
    padding: 10px;
    width: 40%;
    color: #ffd017;
    border-style: solid;
}

#shopPage {
    background-color: white;
    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);

}

  </style>
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  
</body>
</html>